services:
  mysql:
    image: mysql:8.4
    container_name: prguard-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: prguard
      MYSQL_USER: prguard
      MYSQL_PASSWORD: prguard_dev_password
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - prguard_mysql_data:/var/lib/mysql
      - ./infra/mysql/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "prguard", "-pprguard_dev_password"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: prguard-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - prguard_redis_data:/data

volumes:
  prguard_mysql_data:
  prguard_redis_data:
